/* Generated by Yosys 0.57+148 (git sha1 259bd6fb3, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "mac_pe" *)
(* src = "mac_pe.v:3.1-128.10" *)
module \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe (clk, rst_n, a, a_valid, a_ready, b, b_valid, b_ready, a_out, a_out_valid, a_out_ready, b_out, b_out_valid, b_out_ready, out, out_valid, out_ready);
  (* src = "mac_pe.v:8.37-8.40" *)
  input clk;
  wire clk;
  (* src = "mac_pe.v:9.37-9.42" *)
  input rst_n;
  wire rst_n;
  (* src = "mac_pe.v:12.37-12.38" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "mac_pe.v:13.37-13.44" *)
  input a_valid;
  wire a_valid;
  (* src = "mac_pe.v:14.37-14.44" *)
  output a_ready;
  wire a_ready;
  (* src = "mac_pe.v:16.37-16.38" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "mac_pe.v:17.37-17.44" *)
  input b_valid;
  wire b_valid;
  (* src = "mac_pe.v:18.37-18.44" *)
  output b_ready;
  wire b_ready;
  (* src = "mac_pe.v:21.37-21.42" *)
  output [7:0] a_out;
  wire [7:0] a_out;
  (* src = "mac_pe.v:22.37-22.48" *)
  output a_out_valid;
  wire a_out_valid;
  (* src = "mac_pe.v:23.37-23.48" *)
  input a_out_ready;
  wire a_out_ready;
  (* src = "mac_pe.v:25.37-25.42" *)
  output [7:0] b_out;
  wire [7:0] b_out;
  (* src = "mac_pe.v:26.37-26.48" *)
  output b_out_valid;
  wire b_out_valid;
  (* src = "mac_pe.v:27.37-27.48" *)
  input b_out_ready;
  wire b_out_ready;
  (* src = "mac_pe.v:30.37-30.40" *)
  output [31:0] out;
  wire [31:0] out;
  (* src = "mac_pe.v:31.37-31.46" *)
  output out_valid;
  wire out_valid;
  (* src = "mac_pe.v:32.37-32.46" *)
  input out_ready;
  wire out_ready;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  (* src = "mac_pe.v:37.22-37.27" *)
  wire [7:0] a_reg;
  wire [6:0] a_signed;
  (* src = "mac_pe.v:39.21-39.28" *)
  wire [31:0] acc_reg;
  (* src = "mac_pe.v:38.22-38.27" *)
  wire [7:0] b_reg;
  wire [6:0] b_signed;
  (* src = "mac_pe.v:36.9-36.15" *)
  wire have_a;
  (* src = "mac_pe.v:36.17-36.23" *)
  wire have_b;
  (* src = "mac_pe.v:53.29-53.36" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] mul_ext;
  (* src = "mac_pe.v:49.32-49.42" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] mul_result;
  sky130_fd_sc_hd__clkinv_1 _415_ (
    .A(out_ready),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _416_ (
    .A(have_b),
    .B(a_out_ready),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _417_ (
    .A(have_a),
    .B(_102_),
    .Y(a_ready)
  );
  sky130_fd_sc_hd__nand2_1 _418_ (
    .A(have_a),
    .B(b_out_ready),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _419_ (
    .A(have_b),
    .B(_103_),
    .Y(b_ready)
  );
  sky130_fd_sc_hd__nand4_1 _420_ (
    .A(have_b),
    .B(have_a),
    .C(a_out_ready),
    .D(b_out_ready),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor2b_1 _421_ (
    .A(have_b),
    .B_N(b_valid),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a21o_1 _422_ (
    .A1(have_b),
    .A2(_104_),
    .B1(_105_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nor2b_1 _423_ (
    .A(have_a),
    .B_N(a_valid),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a21o_1 _424_ (
    .A1(have_a),
    .A2(_104_),
    .B1(_106_),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2i_1 _425_ (
    .A0(_104_),
    .A1(out_ready),
    .S(out_valid),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a21oi_1 _426_ (
    .A1(out_valid),
    .A2(_101_),
    .B1(_104_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _427_ (
    .A(out[0]),
    .B(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _428_ (
    .A(b_reg[0]),
    .B(a_reg[0]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__and3_1 _429_ (
    .A(b_reg[0]),
    .B(a_reg[0]),
    .C(acc_reg[0]),
    .X(_110_)
  );
  sky130_fd_sc_hd__xor2_1 _430_ (
    .A(acc_reg[0]),
    .B(_109_),
    .X(_111_)
  );
  sky130_fd_sc_hd__a21oi_1 _431_ (
    .A1(_107_),
    .A2(_111_),
    .B1(_108_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _432_ (
    .A(out[1]),
    .B(_107_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(b_reg[1]),
    .B(a_reg[1]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nor2_1 _434_ (
    .A(_109_),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a22oi_1 _435_ (
    .A1(a_reg[0]),
    .A2(b_reg[1]),
    .B1(a_reg[1]),
    .B2(b_reg[0]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nor2_1 _436_ (
    .A(_114_),
    .B(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__xnor2_1 _437_ (
    .A(acc_reg[1]),
    .B(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__xor2_1 _438_ (
    .A(_110_),
    .B(_117_),
    .X(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _439_ (
    .A1(_107_),
    .A2(_118_),
    .B1(_112_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _440_ (
    .A(out[2]),
    .B(_107_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__maj3_1 _441_ (
    .A(acc_reg[1]),
    .B(_110_),
    .C(_116_),
    .X(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(b_reg[0]),
    .B(a_reg[2]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand4_1 _443_ (
    .A(b_reg[0]),
    .B(b_reg[1]),
    .C(a_reg[1]),
    .D(a_reg[2]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a22oi_1 _444_ (
    .A1(b_reg[1]),
    .A2(a_reg[1]),
    .B1(a_reg[2]),
    .B2(b_reg[0]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__xor2_1 _445_ (
    .A(_113_),
    .B(_121_),
    .X(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _446_ (
    .A(a_reg[0]),
    .B(b_reg[2]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nor3b_1 _447_ (
    .A(_125_),
    .B(_123_),
    .C_N(_122_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand3_1 _448_ (
    .A(a_reg[0]),
    .B(b_reg[2]),
    .C(_124_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xnor2_1 _449_ (
    .A(_124_),
    .B(_125_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(_114_),
    .B(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__xor2_1 _451_ (
    .A(_114_),
    .B(_128_),
    .X(_130_)
  );
  sky130_fd_sc_hd__xor2_1 _452_ (
    .A(acc_reg[2]),
    .B(_130_),
    .X(_131_)
  );
  sky130_fd_sc_hd__xnor2_1 _453_ (
    .A(_120_),
    .B(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _454_ (
    .A1(_107_),
    .A2(_132_),
    .B1(_119_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _455_ (
    .A(out[3]),
    .B(_107_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__maj3_1 _456_ (
    .A(acc_reg[2]),
    .B(_120_),
    .C(_130_),
    .X(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _457_ (
    .A(b_reg[1]),
    .B(a_reg[3]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand4_1 _458_ (
    .A(b_reg[0]),
    .B(b_reg[1]),
    .C(a_reg[2]),
    .D(a_reg[3]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a22o_1 _459_ (
    .A1(b_reg[1]),
    .A2(a_reg[2]),
    .B1(a_reg[3]),
    .B2(b_reg[0]),
    .X(_137_)
  );
  sky130_fd_sc_hd__and2_0 _460_ (
    .A(_136_),
    .B(_137_),
    .X(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _461_ (
    .A(a_reg[1]),
    .B(b_reg[3]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand4_1 _462_ (
    .A(a_reg[0]),
    .B(a_reg[1]),
    .C(b_reg[2]),
    .D(b_reg[3]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a22o_1 _463_ (
    .A1(a_reg[1]),
    .A2(b_reg[2]),
    .B1(b_reg[3]),
    .B2(a_reg[0]),
    .X(_141_)
  );
  sky130_fd_sc_hd__and2_0 _464_ (
    .A(_140_),
    .B(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__nand4_1 _465_ (
    .A(_136_),
    .B(_137_),
    .C(_140_),
    .D(_141_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__xnor2_1 _466_ (
    .A(_138_),
    .B(_142_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__xnor3_1 _467_ (
    .A(_126_),
    .B(_138_),
    .C(_142_),
    .X(_145_)
  );
  sky130_fd_sc_hd__xor2_1 _468_ (
    .A(_122_),
    .B(_145_),
    .X(_146_)
  );
  sky130_fd_sc_hd__nand3_1 _469_ (
    .A(_114_),
    .B(_128_),
    .C(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__xnor2_1 _470_ (
    .A(_129_),
    .B(_146_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__xnor2_1 _471_ (
    .A(acc_reg[3]),
    .B(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__xor2_1 _472_ (
    .A(_134_),
    .B(_149_),
    .X(_150_)
  );
  sky130_fd_sc_hd__a21oi_1 _473_ (
    .A1(_107_),
    .A2(_150_),
    .B1(_133_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _474_ (
    .A(out[4]),
    .B(_107_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__maj3_1 _475_ (
    .A(acc_reg[3]),
    .B(_134_),
    .C(_148_),
    .X(_152_)
  );
  sky130_fd_sc_hd__a21oi_1 _476_ (
    .A1(_122_),
    .A2(_127_),
    .B1(_144_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand2_1 _477_ (
    .A(b_reg[0]),
    .B(a_reg[4]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__xnor3_1 _478_ (
    .A(_135_),
    .B(_140_),
    .C(_154_),
    .X(_155_)
  );
  sky130_fd_sc_hd__nand2_1 _479_ (
    .A(b_reg[2]),
    .B(a_reg[2]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand2_1 _480_ (
    .A(a_reg[0]),
    .B(b_reg[4]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _481_ (
    .A(a_reg[1]),
    .B(b_reg[4]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__xnor3_1 _482_ (
    .A(_139_),
    .B(_156_),
    .C(_157_),
    .X(_159_)
  );
  sky130_fd_sc_hd__nand2_1 _483_ (
    .A(_155_),
    .B(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__xnor2_1 _484_ (
    .A(_155_),
    .B(_159_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__xnor3_1 _485_ (
    .A(_143_),
    .B(_155_),
    .C(_159_),
    .X(_162_)
  );
  sky130_fd_sc_hd__xnor2_1 _486_ (
    .A(_136_),
    .B(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nor2_1 _487_ (
    .A(_153_),
    .B(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _488_ (
    .A(_153_),
    .B(_163_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__xor2_1 _489_ (
    .A(_153_),
    .B(_163_),
    .X(_166_)
  );
  sky130_fd_sc_hd__xnor2_1 _490_ (
    .A(_147_),
    .B(_166_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__xor2_1 _491_ (
    .A(acc_reg[4]),
    .B(_167_),
    .X(_168_)
  );
  sky130_fd_sc_hd__xnor2_1 _492_ (
    .A(_152_),
    .B(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a21oi_1 _493_ (
    .A1(_107_),
    .A2(_169_),
    .B1(_151_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _494_ (
    .A(out[5]),
    .B(_107_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__maj3_1 _495_ (
    .A(acc_reg[4]),
    .B(_152_),
    .C(_167_),
    .X(_171_)
  );
  sky130_fd_sc_hd__o21ai_0 _496_ (
    .A1(_147_),
    .A2(_164_),
    .B1(_165_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _497_ (
    .A1(_136_),
    .A2(_143_),
    .B1(_161_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__maj3_1 _498_ (
    .A(_135_),
    .B(_140_),
    .C(_154_),
    .X(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _499_ (
    .A(b_reg[0]),
    .B(a_reg[5]),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nand2_1 _500_ (
    .A(b_reg[1]),
    .B(a_reg[4]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__maj3_1 _501_ (
    .A(_139_),
    .B(_156_),
    .C(_157_),
    .X(_177_)
  );
  sky130_fd_sc_hd__xor3_1 _502_ (
    .A(_175_),
    .B(_176_),
    .C(_177_),
    .X(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _503_ (
    .A(b_reg[2]),
    .B(a_reg[3]),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nand2_1 _504_ (
    .A(a_reg[2]),
    .B(b_reg[3]),
    .Y(_180_)
  );
  sky130_fd_sc_hd__xor3_1 _505_ (
    .A(_158_),
    .B(_179_),
    .C(_180_),
    .X(_181_)
  );
  sky130_fd_sc_hd__nand2_1 _506_ (
    .A(a_reg[0]),
    .B(b_reg[5]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__or2_0 _507_ (
    .A(_181_),
    .B(_182_),
    .X(_183_)
  );
  sky130_fd_sc_hd__xnor2_1 _508_ (
    .A(_181_),
    .B(_182_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nor2_1 _509_ (
    .A(_178_),
    .B(_184_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__xnor2_1 _510_ (
    .A(_178_),
    .B(_184_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__xnor3_1 _511_ (
    .A(_160_),
    .B(_178_),
    .C(_184_),
    .X(_187_)
  );
  sky130_fd_sc_hd__xnor2_1 _512_ (
    .A(_174_),
    .B(_187_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__xnor2_1 _513_ (
    .A(_173_),
    .B(_188_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__xnor2_1 _514_ (
    .A(_172_),
    .B(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__xnor3_1 _515_ (
    .A(acc_reg[5]),
    .B(_171_),
    .C(_190_),
    .X(_191_)
  );
  sky130_fd_sc_hd__a21oi_1 _516_ (
    .A1(_107_),
    .A2(_191_),
    .B1(_170_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__maj3_1 _517_ (
    .A(acc_reg[5]),
    .B(_171_),
    .C(_190_),
    .X(_192_)
  );
  sky130_fd_sc_hd__maj3_1 _518_ (
    .A(_172_),
    .B(_173_),
    .C(_188_),
    .X(_193_)
  );
  sky130_fd_sc_hd__maj3_1 _519_ (
    .A(_160_),
    .B(_174_),
    .C(_186_),
    .X(_194_)
  );
  sky130_fd_sc_hd__maj3_1 _520_ (
    .A(_175_),
    .B(_176_),
    .C(_177_),
    .X(_195_)
  );
  sky130_fd_sc_hd__nand2_1 _521_ (
    .A(b_reg[0]),
    .B(a_reg[6]),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nand2_1 _522_ (
    .A(b_reg[1]),
    .B(a_reg[5]),
    .Y(_197_)
  );
  sky130_fd_sc_hd__maj3_1 _523_ (
    .A(_158_),
    .B(_179_),
    .C(_180_),
    .X(_198_)
  );
  sky130_fd_sc_hd__xnor2_1 _524_ (
    .A(_197_),
    .B(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__xnor2_1 _525_ (
    .A(_196_),
    .B(_199_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nand2_1 _526_ (
    .A(b_reg[2]),
    .B(a_reg[4]),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand2_1 _527_ (
    .A(a_reg[3]),
    .B(b_reg[4]),
    .Y(_202_)
  );
  sky130_fd_sc_hd__and4_1 _528_ (
    .A(a_reg[2]),
    .B(b_reg[3]),
    .C(a_reg[3]),
    .D(b_reg[4]),
    .X(_203_)
  );
  sky130_fd_sc_hd__a22oi_1 _529_ (
    .A1(b_reg[3]),
    .A2(a_reg[3]),
    .B1(b_reg[4]),
    .B2(a_reg[2]),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor2_1 _530_ (
    .A(_203_),
    .B(_204_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__or3_1 _531_ (
    .A(_201_),
    .B(_203_),
    .C(_204_),
    .X(_206_)
  );
  sky130_fd_sc_hd__o21ai_0 _532_ (
    .A1(_203_),
    .A2(_204_),
    .B1(_201_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nand2_1 _533_ (
    .A(a_reg[1]),
    .B(b_reg[6]),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nand4_1 _534_ (
    .A(a_reg[0]),
    .B(a_reg[1]),
    .C(b_reg[5]),
    .D(b_reg[6]),
    .Y(_209_)
  );
  sky130_fd_sc_hd__a22o_1 _535_ (
    .A1(a_reg[1]),
    .A2(b_reg[5]),
    .B1(b_reg[6]),
    .B2(a_reg[0]),
    .X(_210_)
  );
  sky130_fd_sc_hd__nand2_1 _536_ (
    .A(_209_),
    .B(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand4_1 _537_ (
    .A(_206_),
    .B(_207_),
    .C(_209_),
    .D(_210_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__xnor3_1 _538_ (
    .A(_201_),
    .B(_205_),
    .C(_211_),
    .X(_213_)
  );
  sky130_fd_sc_hd__xnor2_1 _539_ (
    .A(_183_),
    .B(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__xnor2_1 _540_ (
    .A(_200_),
    .B(_214_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__xnor3_1 _541_ (
    .A(_185_),
    .B(_200_),
    .C(_214_),
    .X(_216_)
  );
  sky130_fd_sc_hd__xor2_1 _542_ (
    .A(_195_),
    .B(_216_),
    .X(_217_)
  );
  sky130_fd_sc_hd__nor2b_1 _543_ (
    .A(_194_),
    .B_N(_217_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__xnor2_1 _544_ (
    .A(_194_),
    .B(_217_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__xor2_1 _545_ (
    .A(_193_),
    .B(_219_),
    .X(_220_)
  );
  sky130_fd_sc_hd__xnor3_1 _546_ (
    .A(acc_reg[6]),
    .B(_192_),
    .C(_220_),
    .X(_221_)
  );
  sky130_fd_sc_hd__nor2_1 _547_ (
    .A(out[6]),
    .B(_107_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__a21oi_1 _548_ (
    .A1(_107_),
    .A2(_221_),
    .B1(_222_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _549_ (
    .A(out[7]),
    .B(_107_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__maj3_1 _550_ (
    .A(acc_reg[6]),
    .B(_192_),
    .C(_220_),
    .X(_224_)
  );
  sky130_fd_sc_hd__a21oi_1 _551_ (
    .A1(_193_),
    .A2(_219_),
    .B1(_218_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__o32a_1 _552_ (
    .A1(_178_),
    .A2(_184_),
    .A3(_215_),
    .B1(_216_),
    .B2(_195_),
    .X(_226_)
  );
  sky130_fd_sc_hd__maj3_1 _553_ (
    .A(_183_),
    .B(_200_),
    .C(_213_),
    .X(_227_)
  );
  sky130_fd_sc_hd__nand2_1 _554_ (
    .A(a_reg[0]),
    .B(b_reg[7]),
    .Y(_228_)
  );
  sky130_fd_sc_hd__xor2_1 _555_ (
    .A(_208_),
    .B(_228_),
    .X(_229_)
  );
  sky130_fd_sc_hd__nand2_1 _556_ (
    .A(b_reg[3]),
    .B(a_reg[4]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__xor2_1 _557_ (
    .A(_202_),
    .B(_230_),
    .X(_231_)
  );
  sky130_fd_sc_hd__xnor2_1 _558_ (
    .A(_229_),
    .B(_231_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nand2_1 _559_ (
    .A(a_reg[2]),
    .B(b_reg[5]),
    .Y(_233_)
  );
  sky130_fd_sc_hd__mux2i_1 _560_ (
    .A0(a_reg[2]),
    .A1(_233_),
    .S(_209_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nand2_1 _561_ (
    .A(b_reg[2]),
    .B(a_reg[5]),
    .Y(_235_)
  );
  sky130_fd_sc_hd__xor2_1 _562_ (
    .A(_234_),
    .B(_235_),
    .X(_236_)
  );
  sky130_fd_sc_hd__xnor2_1 _563_ (
    .A(_232_),
    .B(_236_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__maj3_1 _564_ (
    .A(_196_),
    .B(_197_),
    .C(_198_),
    .X(_238_)
  );
  sky130_fd_sc_hd__o21ai_0 _565_ (
    .A1(_180_),
    .A2(_202_),
    .B1(_206_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nand2_1 _566_ (
    .A(b_reg[0]),
    .B(a_reg[7]),
    .Y(_240_)
  );
  sky130_fd_sc_hd__nand2_1 _567_ (
    .A(b_reg[1]),
    .B(a_reg[6]),
    .Y(_241_)
  );
  sky130_fd_sc_hd__xnor2_1 _568_ (
    .A(_240_),
    .B(_241_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__xnor2_1 _569_ (
    .A(_239_),
    .B(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__xnor2_1 _570_ (
    .A(_237_),
    .B(_243_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__xnor2_1 _571_ (
    .A(_212_),
    .B(_238_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__xnor2_1 _572_ (
    .A(_244_),
    .B(_245_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__xnor2_1 _573_ (
    .A(_227_),
    .B(_246_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__xnor2_1 _574_ (
    .A(_226_),
    .B(_247_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__xnor2_1 _575_ (
    .A(_225_),
    .B(_248_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__xor2_1 _576_ (
    .A(acc_reg[7]),
    .B(_249_),
    .X(_250_)
  );
  sky130_fd_sc_hd__xnor2_1 _577_ (
    .A(_224_),
    .B(_250_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__a21oi_1 _578_ (
    .A1(_107_),
    .A2(_251_),
    .B1(_223_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__maj3_1 _579_ (
    .A(acc_reg[7]),
    .B(_224_),
    .C(_249_),
    .X(_252_)
  );
  sky130_fd_sc_hd__and2_0 _580_ (
    .A(acc_reg[8]),
    .B(_249_),
    .X(_253_)
  );
  sky130_fd_sc_hd__xor2_1 _581_ (
    .A(acc_reg[8]),
    .B(_249_),
    .X(_254_)
  );
  sky130_fd_sc_hd__xnor2_1 _582_ (
    .A(_252_),
    .B(_254_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__nor2_1 _583_ (
    .A(out[8]),
    .B(_107_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__a21oi_1 _584_ (
    .A1(_107_),
    .A2(_255_),
    .B1(_256_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__a21oi_1 _585_ (
    .A1(_252_),
    .A2(_254_),
    .B1(_253_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nor2_1 _586_ (
    .A(acc_reg[9]),
    .B(_249_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__xor2_1 _587_ (
    .A(acc_reg[9]),
    .B(_249_),
    .X(_259_)
  );
  sky130_fd_sc_hd__xor2_1 _588_ (
    .A(_257_),
    .B(_259_),
    .X(_260_)
  );
  sky130_fd_sc_hd__nor2_1 _589_ (
    .A(out[9]),
    .B(_107_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__a21oi_1 _590_ (
    .A1(_107_),
    .A2(_260_),
    .B1(_261_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _591_ (
    .A(acc_reg[10]),
    .B(_249_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__nand2_1 _592_ (
    .A(acc_reg[10]),
    .B(_249_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2b_1 _593_ (
    .A(_262_),
    .B_N(_263_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__a221oi_1 _594_ (
    .A1(acc_reg[9]),
    .A2(_249_),
    .B1(_252_),
    .B2(_254_),
    .C1(_253_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__nor2_1 _595_ (
    .A(_258_),
    .B(_265_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nand2_1 _596_ (
    .A(_264_),
    .B(_266_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__xnor2_1 _597_ (
    .A(_264_),
    .B(_266_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nor2_1 _598_ (
    .A(out[10]),
    .B(_107_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__a21oi_1 _599_ (
    .A1(_107_),
    .A2(_268_),
    .B1(_269_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _600_ (
    .A(_263_),
    .B(_267_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__or2_0 _601_ (
    .A(acc_reg[11]),
    .B(_249_),
    .X(_271_)
  );
  sky130_fd_sc_hd__nand2_1 _602_ (
    .A(acc_reg[11]),
    .B(_249_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__and2_0 _603_ (
    .A(_271_),
    .B(_272_),
    .X(_273_)
  );
  sky130_fd_sc_hd__xnor2_1 _604_ (
    .A(_270_),
    .B(_273_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__nor2_1 _605_ (
    .A(out[11]),
    .B(_107_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__a21oi_1 _606_ (
    .A1(_107_),
    .A2(_274_),
    .B1(_275_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor2_1 _607_ (
    .A(acc_reg[12]),
    .B(_249_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__and2_0 _608_ (
    .A(acc_reg[12]),
    .B(_249_),
    .X(_277_)
  );
  sky130_fd_sc_hd__nor2_1 _609_ (
    .A(_276_),
    .B(_277_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__o311ai_0 _610_ (
    .A1(_258_),
    .A2(_262_),
    .A3(_265_),
    .B1(_272_),
    .C1(_263_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__and2_0 _611_ (
    .A(_271_),
    .B(_279_),
    .X(_280_)
  );
  sky130_fd_sc_hd__xnor2_1 _612_ (
    .A(_278_),
    .B(_280_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nor2_1 _613_ (
    .A(out[12]),
    .B(_107_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__a21oi_1 _614_ (
    .A1(_107_),
    .A2(_281_),
    .B1(_282_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21oi_1 _615_ (
    .A1(_278_),
    .A2(_280_),
    .B1(_277_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__nor2_1 _616_ (
    .A(acc_reg[13]),
    .B(_249_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__and2_0 _617_ (
    .A(acc_reg[13]),
    .B(_249_),
    .X(_285_)
  );
  sky130_fd_sc_hd__nor2_1 _618_ (
    .A(_284_),
    .B(_285_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__xor2_1 _619_ (
    .A(_283_),
    .B(_286_),
    .X(_287_)
  );
  sky130_fd_sc_hd__nor2_1 _620_ (
    .A(out[13]),
    .B(_107_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__a21oi_1 _621_ (
    .A1(_107_),
    .A2(_287_),
    .B1(_288_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _622_ (
    .A(acc_reg[14]),
    .B(_249_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__xnor2_1 _623_ (
    .A(acc_reg[14]),
    .B(_249_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__a311oi_1 _624_ (
    .A1(_271_),
    .A2(_278_),
    .A3(_279_),
    .B1(_285_),
    .C1(_277_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__or3_1 _625_ (
    .A(_284_),
    .B(_290_),
    .C(_291_),
    .X(_292_)
  );
  sky130_fd_sc_hd__o21ai_0 _626_ (
    .A1(_284_),
    .A2(_291_),
    .B1(_290_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__nand2_1 _627_ (
    .A(_292_),
    .B(_293_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__nor2_1 _628_ (
    .A(out[14]),
    .B(_107_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__a21oi_1 _629_ (
    .A1(_107_),
    .A2(_294_),
    .B1(_295_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o31ai_1 _630_ (
    .A1(_284_),
    .A2(_290_),
    .A3(_291_),
    .B1(_289_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__or2_0 _631_ (
    .A(acc_reg[15]),
    .B(_249_),
    .X(_297_)
  );
  sky130_fd_sc_hd__nand2_1 _632_ (
    .A(acc_reg[15]),
    .B(_249_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__clkinv_1 _633_ (
    .A(_298_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__and2_0 _634_ (
    .A(_297_),
    .B(_298_),
    .X(_300_)
  );
  sky130_fd_sc_hd__xnor2_1 _635_ (
    .A(_296_),
    .B(_300_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__nor2_1 _636_ (
    .A(out[15]),
    .B(_107_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__a21oi_1 _637_ (
    .A1(_107_),
    .A2(_301_),
    .B1(_302_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _638_ (
    .A(acc_reg[16]),
    .B(_249_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__xor2_1 _639_ (
    .A(acc_reg[16]),
    .B(_249_),
    .X(_304_)
  );
  sky130_fd_sc_hd__o21ai_0 _640_ (
    .A1(_296_),
    .A2(_299_),
    .B1(_297_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__o211ai_1 _641_ (
    .A1(_296_),
    .A2(_299_),
    .B1(_304_),
    .C1(_297_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__xor2_1 _642_ (
    .A(_304_),
    .B(_305_),
    .X(_307_)
  );
  sky130_fd_sc_hd__nor2_1 _643_ (
    .A(out[16]),
    .B(_107_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__a21oi_1 _644_ (
    .A1(_107_),
    .A2(_307_),
    .B1(_308_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _645_ (
    .A(_303_),
    .B(_306_),
    .Y(_309_)
  );
  sky130_fd_sc_hd__xnor2_1 _646_ (
    .A(acc_reg[17]),
    .B(_249_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__xor2_1 _647_ (
    .A(_309_),
    .B(_310_),
    .X(_311_)
  );
  sky130_fd_sc_hd__nor2_1 _648_ (
    .A(out[17]),
    .B(_107_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__a21oi_1 _649_ (
    .A1(_107_),
    .A2(_311_),
    .B1(_312_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__o21ai_0 _650_ (
    .A1(acc_reg[16]),
    .A2(acc_reg[17]),
    .B1(_249_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__o21a_1 _651_ (
    .A1(_306_),
    .A2(_310_),
    .B1(_313_),
    .X(_314_)
  );
  sky130_fd_sc_hd__nor2_1 _652_ (
    .A(acc_reg[18]),
    .B(_249_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__nand2_1 _653_ (
    .A(acc_reg[18]),
    .B(_249_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__nor2b_1 _654_ (
    .A(_315_),
    .B_N(_316_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__xnor2_1 _655_ (
    .A(_314_),
    .B(_317_),
    .Y(_318_)
  );
  sky130_fd_sc_hd__mux2_1 _656_ (
    .A0(out[18]),
    .A1(_318_),
    .S(_107_),
    .X(_021_)
  );
  sky130_fd_sc_hd__o21ai_0 _657_ (
    .A1(_314_),
    .A2(_315_),
    .B1(_316_),
    .Y(_319_)
  );
  sky130_fd_sc_hd__xor2_1 _658_ (
    .A(acc_reg[19]),
    .B(_249_),
    .X(_320_)
  );
  sky130_fd_sc_hd__xor2_1 _659_ (
    .A(_319_),
    .B(_320_),
    .X(_321_)
  );
  sky130_fd_sc_hd__mux2_1 _660_ (
    .A0(out[19]),
    .A1(_321_),
    .S(_107_),
    .X(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _661_ (
    .A(out[20]),
    .B(_107_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__nand2_1 _662_ (
    .A(_317_),
    .B(_320_),
    .Y(_323_)
  );
  sky130_fd_sc_hd__o41ai_1 _663_ (
    .A1(acc_reg[16]),
    .A2(acc_reg[17]),
    .A3(acc_reg[18]),
    .A4(acc_reg[19]),
    .B1(_249_),
    .Y(_324_)
  );
  sky130_fd_sc_hd__o31ai_1 _664_ (
    .A1(_306_),
    .A2(_310_),
    .A3(_323_),
    .B1(_324_),
    .Y(_325_)
  );
  sky130_fd_sc_hd__nand2_1 _665_ (
    .A(acc_reg[20]),
    .B(_249_),
    .Y(_326_)
  );
  sky130_fd_sc_hd__xor2_1 _666_ (
    .A(acc_reg[20]),
    .B(_249_),
    .X(_327_)
  );
  sky130_fd_sc_hd__nand2_1 _667_ (
    .A(_325_),
    .B(_327_),
    .Y(_328_)
  );
  sky130_fd_sc_hd__xnor2_1 _668_ (
    .A(_325_),
    .B(_327_),
    .Y(_329_)
  );
  sky130_fd_sc_hd__a21oi_1 _669_ (
    .A1(_107_),
    .A2(_329_),
    .B1(_322_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _670_ (
    .A(_326_),
    .B(_328_),
    .Y(_330_)
  );
  sky130_fd_sc_hd__nand2_1 _671_ (
    .A(acc_reg[21]),
    .B(_249_),
    .Y(_331_)
  );
  sky130_fd_sc_hd__xor2_1 _672_ (
    .A(acc_reg[21]),
    .B(_249_),
    .X(_332_)
  );
  sky130_fd_sc_hd__xnor2_1 _673_ (
    .A(_330_),
    .B(_332_),
    .Y(_333_)
  );
  sky130_fd_sc_hd__nor2_1 _674_ (
    .A(out[21]),
    .B(_107_),
    .Y(_334_)
  );
  sky130_fd_sc_hd__a21oi_1 _675_ (
    .A1(_107_),
    .A2(_333_),
    .B1(_334_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__and3_1 _676_ (
    .A(_325_),
    .B(_327_),
    .C(_332_),
    .X(_335_)
  );
  sky130_fd_sc_hd__nand2_1 _677_ (
    .A(_326_),
    .B(_331_),
    .Y(_336_)
  );
  sky130_fd_sc_hd__nor2_1 _678_ (
    .A(_335_),
    .B(_336_),
    .Y(_337_)
  );
  sky130_fd_sc_hd__nand2_1 _679_ (
    .A(acc_reg[22]),
    .B(_249_),
    .Y(_338_)
  );
  sky130_fd_sc_hd__xor2_1 _680_ (
    .A(acc_reg[22]),
    .B(_249_),
    .X(_339_)
  );
  sky130_fd_sc_hd__o21ai_0 _681_ (
    .A1(_335_),
    .A2(_336_),
    .B1(_339_),
    .Y(_340_)
  );
  sky130_fd_sc_hd__xnor2_1 _682_ (
    .A(_337_),
    .B(_339_),
    .Y(_341_)
  );
  sky130_fd_sc_hd__mux2_1 _683_ (
    .A0(out[22]),
    .A1(_341_),
    .S(_107_),
    .X(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _684_ (
    .A(_338_),
    .B(_340_),
    .Y(_342_)
  );
  sky130_fd_sc_hd__xor2_1 _685_ (
    .A(acc_reg[23]),
    .B(_249_),
    .X(_343_)
  );
  sky130_fd_sc_hd__xor2_1 _686_ (
    .A(_342_),
    .B(_343_),
    .X(_344_)
  );
  sky130_fd_sc_hd__mux2_1 _687_ (
    .A0(out[23]),
    .A1(_344_),
    .S(_107_),
    .X(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _688_ (
    .A(out[24]),
    .B(_107_),
    .Y(_345_)
  );
  sky130_fd_sc_hd__and2_0 _689_ (
    .A(_339_),
    .B(_343_),
    .X(_346_)
  );
  sky130_fd_sc_hd__nand4_1 _690_ (
    .A(_325_),
    .B(_327_),
    .C(_332_),
    .D(_346_),
    .Y(_347_)
  );
  sky130_fd_sc_hd__o41ai_1 _691_ (
    .A1(acc_reg[20]),
    .A2(acc_reg[21]),
    .A3(acc_reg[22]),
    .A4(acc_reg[23]),
    .B1(_249_),
    .Y(_348_)
  );
  sky130_fd_sc_hd__and2_0 _692_ (
    .A(_347_),
    .B(_348_),
    .X(_349_)
  );
  sky130_fd_sc_hd__xnor2_1 _693_ (
    .A(acc_reg[24]),
    .B(_249_),
    .Y(_350_)
  );
  sky130_fd_sc_hd__nor2_1 _694_ (
    .A(_349_),
    .B(_350_),
    .Y(_351_)
  );
  sky130_fd_sc_hd__xnor2_1 _695_ (
    .A(_349_),
    .B(_350_),
    .Y(_352_)
  );
  sky130_fd_sc_hd__a21oi_1 _696_ (
    .A1(_107_),
    .A2(_352_),
    .B1(_345_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _697_ (
    .A1(acc_reg[24]),
    .A2(_249_),
    .B1(_351_),
    .Y(_353_)
  );
  sky130_fd_sc_hd__xnor2_1 _698_ (
    .A(acc_reg[25]),
    .B(_249_),
    .Y(_354_)
  );
  sky130_fd_sc_hd__xnor2_1 _699_ (
    .A(_353_),
    .B(_354_),
    .Y(_355_)
  );
  sky130_fd_sc_hd__nor2_1 _700_ (
    .A(out[25]),
    .B(_107_),
    .Y(_356_)
  );
  sky130_fd_sc_hd__a21oi_1 _701_ (
    .A1(_107_),
    .A2(_355_),
    .B1(_356_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o21ai_0 _702_ (
    .A1(acc_reg[24]),
    .A2(acc_reg[25]),
    .B1(_249_),
    .Y(_357_)
  );
  sky130_fd_sc_hd__o31ai_1 _703_ (
    .A1(_349_),
    .A2(_350_),
    .A3(_354_),
    .B1(_357_),
    .Y(_358_)
  );
  sky130_fd_sc_hd__xor2_1 _704_ (
    .A(acc_reg[26]),
    .B(_249_),
    .X(_359_)
  );
  sky130_fd_sc_hd__xor2_1 _705_ (
    .A(_358_),
    .B(_359_),
    .X(_360_)
  );
  sky130_fd_sc_hd__mux2_1 _706_ (
    .A0(out[26]),
    .A1(_360_),
    .S(_107_),
    .X(_029_)
  );
  sky130_fd_sc_hd__maj3_1 _707_ (
    .A(acc_reg[26]),
    .B(_249_),
    .C(_358_),
    .X(_361_)
  );
  sky130_fd_sc_hd__xor2_1 _708_ (
    .A(acc_reg[27]),
    .B(_249_),
    .X(_362_)
  );
  sky130_fd_sc_hd__xnor2_1 _709_ (
    .A(_361_),
    .B(_362_),
    .Y(_363_)
  );
  sky130_fd_sc_hd__nor2_1 _710_ (
    .A(out[27]),
    .B(_107_),
    .Y(_364_)
  );
  sky130_fd_sc_hd__a21oi_1 _711_ (
    .A1(_107_),
    .A2(_363_),
    .B1(_364_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _712_ (
    .A(_359_),
    .B(_362_),
    .Y(_365_)
  );
  sky130_fd_sc_hd__a2111oi_0 _713_ (
    .A1(_347_),
    .A2(_348_),
    .B1(_350_),
    .C1(_354_),
    .D1(_365_),
    .Y(_366_)
  );
  sky130_fd_sc_hd__o21ai_0 _714_ (
    .A1(acc_reg[26]),
    .A2(acc_reg[27]),
    .B1(_249_),
    .Y(_367_)
  );
  sky130_fd_sc_hd__o21ai_0 _715_ (
    .A1(_357_),
    .A2(_365_),
    .B1(_367_),
    .Y(_368_)
  );
  sky130_fd_sc_hd__nor2_1 _716_ (
    .A(_366_),
    .B(_368_),
    .Y(_369_)
  );
  sky130_fd_sc_hd__nand2_1 _717_ (
    .A(acc_reg[28]),
    .B(_249_),
    .Y(_370_)
  );
  sky130_fd_sc_hd__xor2_1 _718_ (
    .A(acc_reg[28]),
    .B(_249_),
    .X(_371_)
  );
  sky130_fd_sc_hd__o21ai_0 _719_ (
    .A1(_366_),
    .A2(_368_),
    .B1(_371_),
    .Y(_372_)
  );
  sky130_fd_sc_hd__xnor2_1 _720_ (
    .A(_369_),
    .B(_371_),
    .Y(_373_)
  );
  sky130_fd_sc_hd__mux2_1 _721_ (
    .A0(out[28]),
    .A1(_373_),
    .S(_107_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _722_ (
    .A(_370_),
    .B(_372_),
    .Y(_374_)
  );
  sky130_fd_sc_hd__nor2_1 _723_ (
    .A(acc_reg[29]),
    .B(_249_),
    .Y(_375_)
  );
  sky130_fd_sc_hd__nand2_1 _724_ (
    .A(acc_reg[29]),
    .B(_249_),
    .Y(_376_)
  );
  sky130_fd_sc_hd__nor2b_1 _725_ (
    .A(_375_),
    .B_N(_376_),
    .Y(_377_)
  );
  sky130_fd_sc_hd__xnor2_1 _726_ (
    .A(_374_),
    .B(_377_),
    .Y(_378_)
  );
  sky130_fd_sc_hd__nor2_1 _727_ (
    .A(out[29]),
    .B(_107_),
    .Y(_379_)
  );
  sky130_fd_sc_hd__a21oi_1 _728_ (
    .A1(_107_),
    .A2(_378_),
    .B1(_379_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _729_ (
    .A(acc_reg[30]),
    .B(_249_),
    .Y(_380_)
  );
  sky130_fd_sc_hd__xnor2_1 _730_ (
    .A(acc_reg[30]),
    .B(_249_),
    .Y(_381_)
  );
  sky130_fd_sc_hd__a31o_1 _731_ (
    .A1(_370_),
    .A2(_372_),
    .A3(_376_),
    .B1(_375_),
    .X(_382_)
  );
  sky130_fd_sc_hd__xnor2_1 _732_ (
    .A(_381_),
    .B(_382_),
    .Y(_383_)
  );
  sky130_fd_sc_hd__nor2_1 _733_ (
    .A(out[30]),
    .B(_107_),
    .Y(_384_)
  );
  sky130_fd_sc_hd__a21oi_1 _734_ (
    .A1(_107_),
    .A2(_383_),
    .B1(_384_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__o21a_1 _735_ (
    .A1(_381_),
    .A2(_382_),
    .B1(_380_),
    .X(_385_)
  );
  sky130_fd_sc_hd__xor2_1 _736_ (
    .A(acc_reg[31]),
    .B(_249_),
    .X(_386_)
  );
  sky130_fd_sc_hd__xor2_1 _737_ (
    .A(_385_),
    .B(_386_),
    .X(_387_)
  );
  sky130_fd_sc_hd__nor2_1 _738_ (
    .A(out[31]),
    .B(_107_),
    .Y(_388_)
  );
  sky130_fd_sc_hd__a21oi_1 _739_ (
    .A1(_107_),
    .A2(_387_),
    .B1(_388_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__mux2i_1 _740_ (
    .A0(_104_),
    .A1(b_out_ready),
    .S(b_out_valid),
    .Y(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _741_ (
    .A0(b_reg[0]),
    .A1(b_out[0]),
    .S(_104_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _742_ (
    .A0(b_reg[1]),
    .A1(b_out[1]),
    .S(_104_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _743_ (
    .A0(b_reg[2]),
    .A1(b_out[2]),
    .S(_104_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _744_ (
    .A0(b_reg[3]),
    .A1(b_out[3]),
    .S(_104_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _745_ (
    .A0(b_reg[4]),
    .A1(b_out[4]),
    .S(_104_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _746_ (
    .A0(b_reg[5]),
    .A1(b_out[5]),
    .S(_104_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _747_ (
    .A0(b_reg[6]),
    .A1(b_out[6]),
    .S(_104_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _748_ (
    .A0(b_reg[7]),
    .A1(b_out[7]),
    .S(_104_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2i_1 _749_ (
    .A0(_104_),
    .A1(a_out_ready),
    .S(a_out_valid),
    .Y(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _750_ (
    .A0(a_reg[0]),
    .A1(a_out[0]),
    .S(_104_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _751_ (
    .A0(a_reg[1]),
    .A1(a_out[1]),
    .S(_104_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _752_ (
    .A0(a_reg[2]),
    .A1(a_out[2]),
    .S(_104_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _753_ (
    .A0(a_reg[3]),
    .A1(a_out[3]),
    .S(_104_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _754_ (
    .A0(a_reg[4]),
    .A1(a_out[4]),
    .S(_104_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _755_ (
    .A0(a_reg[5]),
    .A1(a_out[5]),
    .S(_104_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _756_ (
    .A0(a_reg[6]),
    .A1(a_out[6]),
    .S(_104_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _757_ (
    .A0(a_reg[7]),
    .A1(a_out[7]),
    .S(_104_),
    .X(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _758_ (
    .A(acc_reg[0]),
    .B(_104_),
    .Y(_389_)
  );
  sky130_fd_sc_hd__o21ai_0 _759_ (
    .A1(_104_),
    .A2(_111_),
    .B1(_389_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _760_ (
    .A(acc_reg[1]),
    .B(_104_),
    .Y(_390_)
  );
  sky130_fd_sc_hd__o21ai_0 _761_ (
    .A1(_104_),
    .A2(_118_),
    .B1(_390_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _762_ (
    .A(acc_reg[2]),
    .B(_104_),
    .Y(_391_)
  );
  sky130_fd_sc_hd__o21ai_0 _763_ (
    .A1(_104_),
    .A2(_132_),
    .B1(_391_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _764_ (
    .A(acc_reg[3]),
    .B(_104_),
    .Y(_392_)
  );
  sky130_fd_sc_hd__o21ai_0 _765_ (
    .A1(_104_),
    .A2(_150_),
    .B1(_392_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _766_ (
    .A(acc_reg[4]),
    .B(_104_),
    .Y(_393_)
  );
  sky130_fd_sc_hd__o21ai_0 _767_ (
    .A1(_104_),
    .A2(_169_),
    .B1(_393_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _768_ (
    .A(acc_reg[5]),
    .B(_104_),
    .Y(_394_)
  );
  sky130_fd_sc_hd__o21ai_0 _769_ (
    .A1(_104_),
    .A2(_191_),
    .B1(_394_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _770_ (
    .A(acc_reg[6]),
    .B(_104_),
    .Y(_395_)
  );
  sky130_fd_sc_hd__o21ai_0 _771_ (
    .A1(_104_),
    .A2(_221_),
    .B1(_395_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _772_ (
    .A(acc_reg[7]),
    .B(_104_),
    .Y(_396_)
  );
  sky130_fd_sc_hd__o21ai_0 _773_ (
    .A1(_104_),
    .A2(_251_),
    .B1(_396_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _774_ (
    .A(acc_reg[8]),
    .B(_104_),
    .Y(_397_)
  );
  sky130_fd_sc_hd__o21ai_0 _775_ (
    .A1(_104_),
    .A2(_255_),
    .B1(_397_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _776_ (
    .A(acc_reg[9]),
    .B(_104_),
    .Y(_398_)
  );
  sky130_fd_sc_hd__o21ai_0 _777_ (
    .A1(_104_),
    .A2(_260_),
    .B1(_398_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _778_ (
    .A(acc_reg[10]),
    .B(_104_),
    .Y(_399_)
  );
  sky130_fd_sc_hd__o21ai_0 _779_ (
    .A1(_104_),
    .A2(_268_),
    .B1(_399_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _780_ (
    .A(acc_reg[11]),
    .B(_104_),
    .Y(_400_)
  );
  sky130_fd_sc_hd__o21ai_0 _781_ (
    .A1(_104_),
    .A2(_274_),
    .B1(_400_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _782_ (
    .A(acc_reg[12]),
    .B(_104_),
    .Y(_401_)
  );
  sky130_fd_sc_hd__o21ai_0 _783_ (
    .A1(_104_),
    .A2(_281_),
    .B1(_401_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _784_ (
    .A(acc_reg[13]),
    .B(_104_),
    .Y(_402_)
  );
  sky130_fd_sc_hd__o21ai_0 _785_ (
    .A1(_104_),
    .A2(_287_),
    .B1(_402_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _786_ (
    .A(acc_reg[14]),
    .B(_104_),
    .Y(_403_)
  );
  sky130_fd_sc_hd__o21ai_0 _787_ (
    .A1(_104_),
    .A2(_294_),
    .B1(_403_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _788_ (
    .A(acc_reg[15]),
    .B(_104_),
    .Y(_404_)
  );
  sky130_fd_sc_hd__o21ai_0 _789_ (
    .A1(_104_),
    .A2(_301_),
    .B1(_404_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _790_ (
    .A(acc_reg[16]),
    .B(_104_),
    .Y(_405_)
  );
  sky130_fd_sc_hd__o21ai_0 _791_ (
    .A1(_104_),
    .A2(_307_),
    .B1(_405_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _792_ (
    .A(acc_reg[17]),
    .B(_104_),
    .Y(_406_)
  );
  sky130_fd_sc_hd__o21ai_0 _793_ (
    .A1(_104_),
    .A2(_311_),
    .B1(_406_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _794_ (
    .A0(_318_),
    .A1(acc_reg[18]),
    .S(_104_),
    .X(_071_)
  );
  sky130_fd_sc_hd__mux2_1 _795_ (
    .A0(_321_),
    .A1(acc_reg[19]),
    .S(_104_),
    .X(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _796_ (
    .A(acc_reg[20]),
    .B(_104_),
    .Y(_407_)
  );
  sky130_fd_sc_hd__o21ai_0 _797_ (
    .A1(_104_),
    .A2(_329_),
    .B1(_407_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _798_ (
    .A(acc_reg[21]),
    .B(_104_),
    .Y(_408_)
  );
  sky130_fd_sc_hd__o21ai_0 _799_ (
    .A1(_104_),
    .A2(_333_),
    .B1(_408_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__mux2_1 _800_ (
    .A0(_341_),
    .A1(acc_reg[22]),
    .S(_104_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_1 _801_ (
    .A0(_344_),
    .A1(acc_reg[23]),
    .S(_104_),
    .X(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _802_ (
    .A(acc_reg[24]),
    .B(_104_),
    .Y(_409_)
  );
  sky130_fd_sc_hd__o21ai_0 _803_ (
    .A1(_104_),
    .A2(_352_),
    .B1(_409_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _804_ (
    .A(acc_reg[25]),
    .B(_104_),
    .Y(_410_)
  );
  sky130_fd_sc_hd__o21ai_0 _805_ (
    .A1(_104_),
    .A2(_355_),
    .B1(_410_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__mux2_1 _806_ (
    .A0(_360_),
    .A1(acc_reg[26]),
    .S(_104_),
    .X(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _807_ (
    .A(acc_reg[27]),
    .B(_104_),
    .Y(_411_)
  );
  sky130_fd_sc_hd__o21ai_0 _808_ (
    .A1(_104_),
    .A2(_363_),
    .B1(_411_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _809_ (
    .A0(_373_),
    .A1(acc_reg[28]),
    .S(_104_),
    .X(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _810_ (
    .A(acc_reg[29]),
    .B(_104_),
    .Y(_412_)
  );
  sky130_fd_sc_hd__o21ai_0 _811_ (
    .A1(_104_),
    .A2(_378_),
    .B1(_412_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _812_ (
    .A(acc_reg[30]),
    .B(_104_),
    .Y(_413_)
  );
  sky130_fd_sc_hd__o21ai_0 _813_ (
    .A1(_104_),
    .A2(_383_),
    .B1(_413_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _814_ (
    .A(acc_reg[31]),
    .B(_104_),
    .Y(_414_)
  );
  sky130_fd_sc_hd__o21ai_0 _815_ (
    .A1(_104_),
    .A2(_387_),
    .B1(_414_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__mux2_1 _816_ (
    .A0(a_reg[0]),
    .A1(a[0]),
    .S(_106_),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2_1 _817_ (
    .A0(a_reg[1]),
    .A1(a[1]),
    .S(_106_),
    .X(_086_)
  );
  sky130_fd_sc_hd__mux2_1 _818_ (
    .A0(a_reg[2]),
    .A1(a[2]),
    .S(_106_),
    .X(_087_)
  );
  sky130_fd_sc_hd__mux2_1 _819_ (
    .A0(a_reg[3]),
    .A1(a[3]),
    .S(_106_),
    .X(_088_)
  );
  sky130_fd_sc_hd__mux2_1 _820_ (
    .A0(a_reg[4]),
    .A1(a[4]),
    .S(_106_),
    .X(_089_)
  );
  sky130_fd_sc_hd__mux2_1 _821_ (
    .A0(a_reg[5]),
    .A1(a[5]),
    .S(_106_),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux2_1 _822_ (
    .A0(a_reg[6]),
    .A1(a[6]),
    .S(_106_),
    .X(_091_)
  );
  sky130_fd_sc_hd__mux2_1 _823_ (
    .A0(a_reg[7]),
    .A1(a[7]),
    .S(_106_),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux2_1 _824_ (
    .A0(b_reg[0]),
    .A1(b[0]),
    .S(_105_),
    .X(_093_)
  );
  sky130_fd_sc_hd__mux2_1 _825_ (
    .A0(b_reg[1]),
    .A1(b[1]),
    .S(_105_),
    .X(_094_)
  );
  sky130_fd_sc_hd__mux2_1 _826_ (
    .A0(b_reg[2]),
    .A1(b[2]),
    .S(_105_),
    .X(_095_)
  );
  sky130_fd_sc_hd__mux2_1 _827_ (
    .A0(b_reg[3]),
    .A1(b[3]),
    .S(_105_),
    .X(_096_)
  );
  sky130_fd_sc_hd__mux2_1 _828_ (
    .A0(b_reg[4]),
    .A1(b[4]),
    .S(_105_),
    .X(_097_)
  );
  sky130_fd_sc_hd__mux2_1 _829_ (
    .A0(b_reg[5]),
    .A1(b[5]),
    .S(_105_),
    .X(_098_)
  );
  sky130_fd_sc_hd__mux2_1 _830_ (
    .A0(b_reg[6]),
    .A1(b[6]),
    .S(_105_),
    .X(_099_)
  );
  sky130_fd_sc_hd__mux2_1 _831_ (
    .A0(b_reg[7]),
    .A1(b[7]),
    .S(_105_),
    .X(_100_)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _832_ (
    .CLK(clk),
    .D(_000_),
    .Q(have_b),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _833_ (
    .CLK(clk),
    .D(_001_),
    .Q(have_a),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _834_ (
    .CLK(clk),
    .D(_002_),
    .Q(out_valid),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _835_ (
    .CLK(clk),
    .D(_003_),
    .Q(out[0]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _836_ (
    .CLK(clk),
    .D(_004_),
    .Q(out[1]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _837_ (
    .CLK(clk),
    .D(_005_),
    .Q(out[2]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _838_ (
    .CLK(clk),
    .D(_006_),
    .Q(out[3]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _839_ (
    .CLK(clk),
    .D(_007_),
    .Q(out[4]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _840_ (
    .CLK(clk),
    .D(_008_),
    .Q(out[5]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _841_ (
    .CLK(clk),
    .D(_009_),
    .Q(out[6]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _842_ (
    .CLK(clk),
    .D(_010_),
    .Q(out[7]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _843_ (
    .CLK(clk),
    .D(_011_),
    .Q(out[8]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _844_ (
    .CLK(clk),
    .D(_012_),
    .Q(out[9]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _845_ (
    .CLK(clk),
    .D(_013_),
    .Q(out[10]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _846_ (
    .CLK(clk),
    .D(_014_),
    .Q(out[11]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _847_ (
    .CLK(clk),
    .D(_015_),
    .Q(out[12]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _848_ (
    .CLK(clk),
    .D(_016_),
    .Q(out[13]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _849_ (
    .CLK(clk),
    .D(_017_),
    .Q(out[14]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _850_ (
    .CLK(clk),
    .D(_018_),
    .Q(out[15]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _851_ (
    .CLK(clk),
    .D(_019_),
    .Q(out[16]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _852_ (
    .CLK(clk),
    .D(_020_),
    .Q(out[17]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _853_ (
    .CLK(clk),
    .D(_021_),
    .Q(out[18]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _854_ (
    .CLK(clk),
    .D(_022_),
    .Q(out[19]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _855_ (
    .CLK(clk),
    .D(_023_),
    .Q(out[20]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _856_ (
    .CLK(clk),
    .D(_024_),
    .Q(out[21]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _857_ (
    .CLK(clk),
    .D(_025_),
    .Q(out[22]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _858_ (
    .CLK(clk),
    .D(_026_),
    .Q(out[23]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _859_ (
    .CLK(clk),
    .D(_027_),
    .Q(out[24]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _860_ (
    .CLK(clk),
    .D(_028_),
    .Q(out[25]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _861_ (
    .CLK(clk),
    .D(_029_),
    .Q(out[26]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _862_ (
    .CLK(clk),
    .D(_030_),
    .Q(out[27]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _863_ (
    .CLK(clk),
    .D(_031_),
    .Q(out[28]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _864_ (
    .CLK(clk),
    .D(_032_),
    .Q(out[29]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _865_ (
    .CLK(clk),
    .D(_033_),
    .Q(out[30]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _866_ (
    .CLK(clk),
    .D(_034_),
    .Q(out[31]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _867_ (
    .CLK(clk),
    .D(_035_),
    .Q(b_out_valid),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _868_ (
    .CLK(clk),
    .D(_036_),
    .Q(b_out[0]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _869_ (
    .CLK(clk),
    .D(_037_),
    .Q(b_out[1]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _870_ (
    .CLK(clk),
    .D(_038_),
    .Q(b_out[2]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _871_ (
    .CLK(clk),
    .D(_039_),
    .Q(b_out[3]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _872_ (
    .CLK(clk),
    .D(_040_),
    .Q(b_out[4]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _873_ (
    .CLK(clk),
    .D(_041_),
    .Q(b_out[5]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _874_ (
    .CLK(clk),
    .D(_042_),
    .Q(b_out[6]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _875_ (
    .CLK(clk),
    .D(_043_),
    .Q(b_out[7]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _876_ (
    .CLK(clk),
    .D(_044_),
    .Q(a_out_valid),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _877_ (
    .CLK(clk),
    .D(_045_),
    .Q(a_out[0]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _878_ (
    .CLK(clk),
    .D(_046_),
    .Q(a_out[1]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _879_ (
    .CLK(clk),
    .D(_047_),
    .Q(a_out[2]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _880_ (
    .CLK(clk),
    .D(_048_),
    .Q(a_out[3]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _881_ (
    .CLK(clk),
    .D(_049_),
    .Q(a_out[4]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _882_ (
    .CLK(clk),
    .D(_050_),
    .Q(a_out[5]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _883_ (
    .CLK(clk),
    .D(_051_),
    .Q(a_out[6]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _884_ (
    .CLK(clk),
    .D(_052_),
    .Q(a_out[7]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _885_ (
    .CLK(clk),
    .D(_053_),
    .Q(acc_reg[0]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _886_ (
    .CLK(clk),
    .D(_054_),
    .Q(acc_reg[1]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _887_ (
    .CLK(clk),
    .D(_055_),
    .Q(acc_reg[2]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _888_ (
    .CLK(clk),
    .D(_056_),
    .Q(acc_reg[3]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _889_ (
    .CLK(clk),
    .D(_057_),
    .Q(acc_reg[4]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _890_ (
    .CLK(clk),
    .D(_058_),
    .Q(acc_reg[5]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _891_ (
    .CLK(clk),
    .D(_059_),
    .Q(acc_reg[6]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _892_ (
    .CLK(clk),
    .D(_060_),
    .Q(acc_reg[7]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _893_ (
    .CLK(clk),
    .D(_061_),
    .Q(acc_reg[8]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _894_ (
    .CLK(clk),
    .D(_062_),
    .Q(acc_reg[9]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _895_ (
    .CLK(clk),
    .D(_063_),
    .Q(acc_reg[10]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _896_ (
    .CLK(clk),
    .D(_064_),
    .Q(acc_reg[11]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _897_ (
    .CLK(clk),
    .D(_065_),
    .Q(acc_reg[12]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _898_ (
    .CLK(clk),
    .D(_066_),
    .Q(acc_reg[13]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _899_ (
    .CLK(clk),
    .D(_067_),
    .Q(acc_reg[14]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _900_ (
    .CLK(clk),
    .D(_068_),
    .Q(acc_reg[15]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _901_ (
    .CLK(clk),
    .D(_069_),
    .Q(acc_reg[16]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _902_ (
    .CLK(clk),
    .D(_070_),
    .Q(acc_reg[17]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _903_ (
    .CLK(clk),
    .D(_071_),
    .Q(acc_reg[18]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _904_ (
    .CLK(clk),
    .D(_072_),
    .Q(acc_reg[19]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _905_ (
    .CLK(clk),
    .D(_073_),
    .Q(acc_reg[20]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _906_ (
    .CLK(clk),
    .D(_074_),
    .Q(acc_reg[21]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _907_ (
    .CLK(clk),
    .D(_075_),
    .Q(acc_reg[22]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _908_ (
    .CLK(clk),
    .D(_076_),
    .Q(acc_reg[23]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _909_ (
    .CLK(clk),
    .D(_077_),
    .Q(acc_reg[24]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _910_ (
    .CLK(clk),
    .D(_078_),
    .Q(acc_reg[25]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _911_ (
    .CLK(clk),
    .D(_079_),
    .Q(acc_reg[26]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _912_ (
    .CLK(clk),
    .D(_080_),
    .Q(acc_reg[27]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _913_ (
    .CLK(clk),
    .D(_081_),
    .Q(acc_reg[28]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _914_ (
    .CLK(clk),
    .D(_082_),
    .Q(acc_reg[29]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _915_ (
    .CLK(clk),
    .D(_083_),
    .Q(acc_reg[30]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _916_ (
    .CLK(clk),
    .D(_084_),
    .Q(acc_reg[31]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _917_ (
    .CLK(clk),
    .D(_085_),
    .Q(a_reg[0]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _918_ (
    .CLK(clk),
    .D(_086_),
    .Q(a_reg[1]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _919_ (
    .CLK(clk),
    .D(_087_),
    .Q(a_reg[2]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _920_ (
    .CLK(clk),
    .D(_088_),
    .Q(a_reg[3]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _921_ (
    .CLK(clk),
    .D(_089_),
    .Q(a_reg[4]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _922_ (
    .CLK(clk),
    .D(_090_),
    .Q(a_reg[5]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _923_ (
    .CLK(clk),
    .D(_091_),
    .Q(a_reg[6]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _924_ (
    .CLK(clk),
    .D(_092_),
    .Q(a_reg[7]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _925_ (
    .CLK(clk),
    .D(_093_),
    .Q(b_reg[0]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _926_ (
    .CLK(clk),
    .D(_094_),
    .Q(b_reg[1]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _927_ (
    .CLK(clk),
    .D(_095_),
    .Q(b_reg[2]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _928_ (
    .CLK(clk),
    .D(_096_),
    .Q(b_reg[3]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _929_ (
    .CLK(clk),
    .D(_097_),
    .Q(b_reg[4]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _930_ (
    .CLK(clk),
    .D(_098_),
    .Q(b_reg[5]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _931_ (
    .CLK(clk),
    .D(_099_),
    .Q(b_reg[6]),
    .RESET_B(rst_n)
  );
  (* src = "mac_pe.v:55.5-126.8" *)
  sky130_fd_sc_hd__dfrtp_1 _932_ (
    .CLK(clk),
    .D(_100_),
    .Q(b_reg[7]),
    .RESET_B(rst_n)
  );
  assign a_signed = a_reg[6:0];
  assign b_signed = b_reg[6:0];
  assign mul_ext[30:7] = { mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31] };
  assign mul_result = { mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[31], mul_ext[6:0] };
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "systolic_top.v:4.1-144.10" *)
module systolic_top(clk, rst_n, a_in, a_in_valid, a_in_ready, b_in, b_in_valid, b_in_ready);
  (* src = "systolic_top.v:11.37-11.40" *)
  input clk;
  wire clk;
  (* src = "systolic_top.v:12.37-12.42" *)
  input rst_n;
  wire rst_n;
  (* src = "systolic_top.v:15.37-15.41" *)
  input [7:0] a_in;
  wire [7:0] a_in;
  (* src = "systolic_top.v:16.37-16.47" *)
  input a_in_valid;
  wire a_in_valid;
  (* src = "systolic_top.v:17.37-17.47" *)
  output a_in_ready;
  wire a_in_ready;
  (* src = "systolic_top.v:19.37-19.41" *)
  input [7:0] b_in;
  wire [7:0] b_in;
  (* src = "systolic_top.v:20.37-20.47" *)
  input b_in_valid;
  wire b_in_valid;
  (* src = "systolic_top.v:21.37-21.47" *)
  output b_in_ready;
  wire b_in_ready;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[0] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[10] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[11] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[12] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[13] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \a_horz[14] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[15] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[16] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[17] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[18] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \a_horz[19] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[1] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[2] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[3] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \a_horz[4] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[5] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[6] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[7] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  wire [7:0] \a_horz[8] ;
  (* src = "systolic_top.v:41.23-41.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \a_horz[9] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[0] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[10] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[11] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[12] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[13] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[14] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[15] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[16] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[17] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[18] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[19] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[1] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[2] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[3] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[4] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[5] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[6] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[7] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[8] ;
  (* src = "systolic_top.v:43.23-43.35" *)
  wire [0:0] \a_horz_ready[9] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[0] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[10] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[11] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[12] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[13] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  (* unused_bits = "0" *)
  wire [0:0] \a_horz_valid[14] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[15] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[16] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[17] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[18] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  (* unused_bits = "0" *)
  wire [0:0] \a_horz_valid[19] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[1] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[2] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[3] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  (* unused_bits = "0" *)
  wire [0:0] \a_horz_valid[4] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[5] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[6] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[7] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  wire [0:0] \a_horz_valid[8] ;
  (* src = "systolic_top.v:42.23-42.35" *)
  (* unused_bits = "0" *)
  wire [0:0] \a_horz_valid[9] ;
  (* src = "systolic_top.v:71.18-71.30" *)
  wire [3:0] a_ready_col0;
  (* src = "systolic_top.v:80.18-80.30" *)
  wire [3:0] b_ready_row0;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[0] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[10] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[11] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[12] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[13] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[14] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[15] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \b_vert[16] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \b_vert[17] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \b_vert[18] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \b_vert[19] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[1] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[2] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[3] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[4] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[5] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[6] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[7] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[8] ;
  (* src = "systolic_top.v:46.23-46.29" *)
  wire [7:0] \b_vert[9] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[0] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[10] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[11] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[12] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[13] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[14] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[15] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[16] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[17] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[18] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[19] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[1] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[2] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[3] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[4] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[5] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[6] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[7] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[8] ;
  (* src = "systolic_top.v:48.23-48.35" *)
  wire [0:0] \b_vert_ready[9] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[0] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[10] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[11] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[12] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[13] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[14] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[15] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  (* unused_bits = "0" *)
  wire [0:0] \b_vert_valid[16] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  (* unused_bits = "0" *)
  wire [0:0] \b_vert_valid[17] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  (* unused_bits = "0" *)
  wire [0:0] \b_vert_valid[18] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  (* unused_bits = "0" *)
  wire [0:0] \b_vert_valid[19] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[1] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[2] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[3] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[4] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[5] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[6] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[7] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[8] ;
  (* src = "systolic_top.v:47.23-47.35" *)
  wire [0:0] \b_vert_valid[9] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[0] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[10] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[11] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[12] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[13] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[14] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[15] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[1] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[2] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[3] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[4] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[5] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[6] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[7] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[8] ;
  (* src = "systolic_top.v:28.22-28.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \out_matrix[9] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[0] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[10] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[11] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[12] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[13] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[14] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[15] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[1] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[2] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[3] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[4] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[5] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[6] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[7] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[8] ;
  (* src = "systolic_top.v:30.22-30.31" *)
  wire [0:0] \out_ready[9] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[0] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[10] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[11] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[12] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[13] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[14] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[15] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[1] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[2] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[3] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[4] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[5] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[6] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[7] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[8] ;
  (* src = "systolic_top.v:29.22-29.31" *)
  (* unused_bits = "0" *)
  wire [0:0] \out_valid[9] ;
  sky130_fd_sc_hd__and4_1 _0_ (
    .A(\a_horz_ready[5] ),
    .B(\a_horz_ready[0] ),
    .C(\a_horz_ready[15] ),
    .D(\a_horz_ready[10] ),
    .X(a_in_ready)
  );
  sky130_fd_sc_hd__and4_1 _1_ (
    .A(\b_vert_ready[1] ),
    .B(\b_vert_ready[0] ),
    .C(\b_vert_ready[3] ),
    .D(\b_vert_ready[2] ),
    .X(b_in_ready)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[0].col[0].pe_inst  (
    .a(a_in),
    .a_out(\a_horz[1] ),
    .a_out_ready(\a_horz_ready[1] ),
    .a_out_valid(\a_horz_valid[1] ),
    .a_ready(\a_horz_ready[0] ),
    .a_valid(a_in_valid),
    .b(b_in),
    .b_out(\b_vert[4] ),
    .b_out_ready(\b_vert_ready[4] ),
    .b_out_valid(\b_vert_valid[4] ),
    .b_ready(\b_vert_ready[0] ),
    .b_valid(b_in_valid),
    .clk(clk),
    .out(\out_matrix[0] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[0] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[0].col[1].pe_inst  (
    .a(\a_horz[1] ),
    .a_out(\a_horz[2] ),
    .a_out_ready(\a_horz_ready[2] ),
    .a_out_valid(\a_horz_valid[2] ),
    .a_ready(\a_horz_ready[1] ),
    .a_valid(\a_horz_valid[1] ),
    .b(b_in),
    .b_out(\b_vert[5] ),
    .b_out_ready(\b_vert_ready[5] ),
    .b_out_valid(\b_vert_valid[5] ),
    .b_ready(\b_vert_ready[1] ),
    .b_valid(b_in_valid),
    .clk(clk),
    .out(\out_matrix[1] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[1] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[0].col[2].pe_inst  (
    .a(\a_horz[2] ),
    .a_out(\a_horz[3] ),
    .a_out_ready(\a_horz_ready[3] ),
    .a_out_valid(\a_horz_valid[3] ),
    .a_ready(\a_horz_ready[2] ),
    .a_valid(\a_horz_valid[2] ),
    .b(b_in),
    .b_out(\b_vert[6] ),
    .b_out_ready(\b_vert_ready[6] ),
    .b_out_valid(\b_vert_valid[6] ),
    .b_ready(\b_vert_ready[2] ),
    .b_valid(b_in_valid),
    .clk(clk),
    .out(\out_matrix[2] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[2] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[0].col[3].pe_inst  (
    .a(\a_horz[3] ),
    .a_out(\a_horz[4] ),
    .a_out_ready(1'h1),
    .a_out_valid(\a_horz_valid[4] ),
    .a_ready(\a_horz_ready[3] ),
    .a_valid(\a_horz_valid[3] ),
    .b(b_in),
    .b_out(\b_vert[7] ),
    .b_out_ready(\b_vert_ready[7] ),
    .b_out_valid(\b_vert_valid[7] ),
    .b_ready(\b_vert_ready[3] ),
    .b_valid(b_in_valid),
    .clk(clk),
    .out(\out_matrix[3] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[3] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[1].col[0].pe_inst  (
    .a(a_in),
    .a_out(\a_horz[6] ),
    .a_out_ready(\a_horz_ready[6] ),
    .a_out_valid(\a_horz_valid[6] ),
    .a_ready(\a_horz_ready[5] ),
    .a_valid(a_in_valid),
    .b(\b_vert[4] ),
    .b_out(\b_vert[8] ),
    .b_out_ready(\b_vert_ready[8] ),
    .b_out_valid(\b_vert_valid[8] ),
    .b_ready(\b_vert_ready[4] ),
    .b_valid(\b_vert_valid[4] ),
    .clk(clk),
    .out(\out_matrix[4] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[4] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[1].col[1].pe_inst  (
    .a(\a_horz[6] ),
    .a_out(\a_horz[7] ),
    .a_out_ready(\a_horz_ready[7] ),
    .a_out_valid(\a_horz_valid[7] ),
    .a_ready(\a_horz_ready[6] ),
    .a_valid(\a_horz_valid[6] ),
    .b(\b_vert[5] ),
    .b_out(\b_vert[9] ),
    .b_out_ready(\b_vert_ready[9] ),
    .b_out_valid(\b_vert_valid[9] ),
    .b_ready(\b_vert_ready[5] ),
    .b_valid(\b_vert_valid[5] ),
    .clk(clk),
    .out(\out_matrix[5] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[5] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[1].col[2].pe_inst  (
    .a(\a_horz[7] ),
    .a_out(\a_horz[8] ),
    .a_out_ready(\a_horz_ready[8] ),
    .a_out_valid(\a_horz_valid[8] ),
    .a_ready(\a_horz_ready[7] ),
    .a_valid(\a_horz_valid[7] ),
    .b(\b_vert[6] ),
    .b_out(\b_vert[10] ),
    .b_out_ready(\b_vert_ready[10] ),
    .b_out_valid(\b_vert_valid[10] ),
    .b_ready(\b_vert_ready[6] ),
    .b_valid(\b_vert_valid[6] ),
    .clk(clk),
    .out(\out_matrix[6] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[6] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[1].col[3].pe_inst  (
    .a(\a_horz[8] ),
    .a_out(\a_horz[9] ),
    .a_out_ready(1'h1),
    .a_out_valid(\a_horz_valid[9] ),
    .a_ready(\a_horz_ready[8] ),
    .a_valid(\a_horz_valid[8] ),
    .b(\b_vert[7] ),
    .b_out(\b_vert[11] ),
    .b_out_ready(\b_vert_ready[11] ),
    .b_out_valid(\b_vert_valid[11] ),
    .b_ready(\b_vert_ready[7] ),
    .b_valid(\b_vert_valid[7] ),
    .clk(clk),
    .out(\out_matrix[7] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[7] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[2].col[0].pe_inst  (
    .a(a_in),
    .a_out(\a_horz[11] ),
    .a_out_ready(\a_horz_ready[11] ),
    .a_out_valid(\a_horz_valid[11] ),
    .a_ready(\a_horz_ready[10] ),
    .a_valid(a_in_valid),
    .b(\b_vert[8] ),
    .b_out(\b_vert[12] ),
    .b_out_ready(\b_vert_ready[12] ),
    .b_out_valid(\b_vert_valid[12] ),
    .b_ready(\b_vert_ready[8] ),
    .b_valid(\b_vert_valid[8] ),
    .clk(clk),
    .out(\out_matrix[8] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[8] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[2].col[1].pe_inst  (
    .a(\a_horz[11] ),
    .a_out(\a_horz[12] ),
    .a_out_ready(\a_horz_ready[12] ),
    .a_out_valid(\a_horz_valid[12] ),
    .a_ready(\a_horz_ready[11] ),
    .a_valid(\a_horz_valid[11] ),
    .b(\b_vert[9] ),
    .b_out(\b_vert[13] ),
    .b_out_ready(\b_vert_ready[13] ),
    .b_out_valid(\b_vert_valid[13] ),
    .b_ready(\b_vert_ready[9] ),
    .b_valid(\b_vert_valid[9] ),
    .clk(clk),
    .out(\out_matrix[9] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[9] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[2].col[2].pe_inst  (
    .a(\a_horz[12] ),
    .a_out(\a_horz[13] ),
    .a_out_ready(\a_horz_ready[13] ),
    .a_out_valid(\a_horz_valid[13] ),
    .a_ready(\a_horz_ready[12] ),
    .a_valid(\a_horz_valid[12] ),
    .b(\b_vert[10] ),
    .b_out(\b_vert[14] ),
    .b_out_ready(\b_vert_ready[14] ),
    .b_out_valid(\b_vert_valid[14] ),
    .b_ready(\b_vert_ready[10] ),
    .b_valid(\b_vert_valid[10] ),
    .clk(clk),
    .out(\out_matrix[10] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[10] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[2].col[3].pe_inst  (
    .a(\a_horz[13] ),
    .a_out(\a_horz[14] ),
    .a_out_ready(1'h1),
    .a_out_valid(\a_horz_valid[14] ),
    .a_ready(\a_horz_ready[13] ),
    .a_valid(\a_horz_valid[13] ),
    .b(\b_vert[11] ),
    .b_out(\b_vert[15] ),
    .b_out_ready(\b_vert_ready[15] ),
    .b_out_valid(\b_vert_valid[15] ),
    .b_ready(\b_vert_ready[11] ),
    .b_valid(\b_vert_valid[11] ),
    .clk(clk),
    .out(\out_matrix[11] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[11] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[3].col[0].pe_inst  (
    .a(a_in),
    .a_out(\a_horz[16] ),
    .a_out_ready(\a_horz_ready[16] ),
    .a_out_valid(\a_horz_valid[16] ),
    .a_ready(\a_horz_ready[15] ),
    .a_valid(a_in_valid),
    .b(\b_vert[12] ),
    .b_out(\b_vert[16] ),
    .b_out_ready(1'h1),
    .b_out_valid(\b_vert_valid[16] ),
    .b_ready(\b_vert_ready[12] ),
    .b_valid(\b_vert_valid[12] ),
    .clk(clk),
    .out(\out_matrix[12] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[12] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[3].col[1].pe_inst  (
    .a(\a_horz[16] ),
    .a_out(\a_horz[17] ),
    .a_out_ready(\a_horz_ready[17] ),
    .a_out_valid(\a_horz_valid[17] ),
    .a_ready(\a_horz_ready[16] ),
    .a_valid(\a_horz_valid[16] ),
    .b(\b_vert[13] ),
    .b_out(\b_vert[17] ),
    .b_out_ready(1'h1),
    .b_out_valid(\b_vert_valid[17] ),
    .b_ready(\b_vert_ready[13] ),
    .b_valid(\b_vert_valid[13] ),
    .clk(clk),
    .out(\out_matrix[13] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[13] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[3].col[2].pe_inst  (
    .a(\a_horz[17] ),
    .a_out(\a_horz[18] ),
    .a_out_ready(\a_horz_ready[18] ),
    .a_out_valid(\a_horz_valid[18] ),
    .a_ready(\a_horz_ready[17] ),
    .a_valid(\a_horz_valid[17] ),
    .b(\b_vert[14] ),
    .b_out(\b_vert[18] ),
    .b_out_ready(1'h1),
    .b_out_valid(\b_vert_valid[18] ),
    .b_ready(\b_vert_ready[14] ),
    .b_valid(\b_vert_valid[14] ),
    .clk(clk),
    .out(\out_matrix[14] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[14] ),
    .rst_n(rst_n)
  );
  (* src = "systolic_top.v:97.19-123.18" *)
  \$paramod$94011fb4afdafa8b55b9dd21b9d112684dc53c6e\mac_pe  \row[3].col[3].pe_inst  (
    .a(\a_horz[18] ),
    .a_out(\a_horz[19] ),
    .a_out_ready(1'h1),
    .a_out_valid(\a_horz_valid[19] ),
    .a_ready(\a_horz_ready[18] ),
    .a_valid(\a_horz_valid[18] ),
    .b(\b_vert[15] ),
    .b_out(\b_vert[19] ),
    .b_out_ready(1'h1),
    .b_out_valid(\b_vert_valid[19] ),
    .b_ready(\b_vert_ready[15] ),
    .b_valid(\b_vert_valid[15] ),
    .clk(clk),
    .out(\out_matrix[15] ),
    .out_ready(1'h1),
    .out_valid(\out_valid[15] ),
    .rst_n(rst_n)
  );
  assign \a_horz[0]  = a_in;
  assign \a_horz[10]  = a_in;
  assign \a_horz[15]  = a_in;
  assign \a_horz[5]  = a_in;
  assign \a_horz_ready[14]  = 1'h1;
  assign \a_horz_ready[19]  = 1'h1;
  assign \a_horz_ready[4]  = 1'h1;
  assign \a_horz_ready[9]  = 1'h1;
  assign \a_horz_valid[0]  = a_in_valid;
  assign \a_horz_valid[10]  = a_in_valid;
  assign \a_horz_valid[15]  = a_in_valid;
  assign \a_horz_valid[5]  = a_in_valid;
  assign a_ready_col0 = { \a_horz_ready[15] , \a_horz_ready[10] , \a_horz_ready[5] , \a_horz_ready[0]  };
  assign b_ready_row0 = { \b_vert_ready[3] , \b_vert_ready[2] , \b_vert_ready[1] , \b_vert_ready[0]  };
  assign \b_vert[0]  = b_in;
  assign \b_vert[1]  = b_in;
  assign \b_vert[2]  = b_in;
  assign \b_vert[3]  = b_in;
  assign \b_vert_ready[16]  = 1'h1;
  assign \b_vert_ready[17]  = 1'h1;
  assign \b_vert_ready[18]  = 1'h1;
  assign \b_vert_ready[19]  = 1'h1;
  assign \b_vert_valid[0]  = b_in_valid;
  assign \b_vert_valid[1]  = b_in_valid;
  assign \b_vert_valid[2]  = b_in_valid;
  assign \b_vert_valid[3]  = b_in_valid;
  assign \out_ready[0]  = 1'h1;
  assign \out_ready[10]  = 1'h1;
  assign \out_ready[11]  = 1'h1;
  assign \out_ready[12]  = 1'h1;
  assign \out_ready[13]  = 1'h1;
  assign \out_ready[14]  = 1'h1;
  assign \out_ready[15]  = 1'h1;
  assign \out_ready[1]  = 1'h1;
  assign \out_ready[2]  = 1'h1;
  assign \out_ready[3]  = 1'h1;
  assign \out_ready[4]  = 1'h1;
  assign \out_ready[5]  = 1'h1;
  assign \out_ready[6]  = 1'h1;
  assign \out_ready[7]  = 1'h1;
  assign \out_ready[8]  = 1'h1;
  assign \out_ready[9]  = 1'h1;
endmodule
